# Generated by Django 3.1.7 on 2021-02-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='recipes.recipetype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Recipe Name')),
                ('ingredients', models.TextField(verbose_name='Recipe Ingredients')),
                ('steps', models.TextField(verbose_name='Recipe Steps')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Recipe Creation Date')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='Date of Last Recipe Modification')),
                ('recipe_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipetype', verbose_name='Recipe Type')),
            ],
            options={
                'ordering': ['-name', '-last_modified'],
                'get_latest_by': ['-last_modified', '-created_at'],
            },
        ),
    ]
