# Generated by Django 3.1.7 on 2021-02-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210223_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredients_json',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='steps',
            new_name='steps_json',
        ),
    ]
